#!/usr/bin/env bash

set -euo pipefail

timeout --signal=TERM --kill-after=1 5 \
    ffmpeg -hide_banner -loglevel error -f v4l2 -i "$1" -vf \
    'select=gte(n\,3),scale=1280:720,format=yuv420p' -frames:v 1 -y "$2"
