#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# --- Simple screenshot script using maim and AwesomeWM API
# --
# -- Accepts `area` and `full` string args
# --
# -- For more details check `man maim`
# --
# -- @author manilarome &lt;gerome.matilla07@gmail.com&gt;
# -- @copyright 2020 manilarome
# -- @script snap
# ----------------------------------------------------------------------------

screenshot_dir=~/Pictures/Screenshots/

# Read display names/modes/positions and screenshot target from config.lua
source <("$HOME/.config/awesome/utilities/read-display-config")

# Check save directory
# Create it if it doesn't exist
function check_dir() {
	if [ ! -d "$screenshot_dir" ];
	then
		mkdir -p "$screenshot_dir"
	fi
}

function is_connected() {
    xrandr | grep -q "^$1 connected"
}

function parse_size() {
    local size="$1"
    DISPLAY_WIDTH="${size%x*}"
    DISPLAY_HEIGHT="${size#*x}"
}

function parse_position() {
    local position="$1"
    DISPLAY_X="${position%x*}"
    DISPLAY_Y="${position#*x}"
}

function geometry_for_display() {
    local mode="$1"
    local position="$2"

    parse_size "$mode"
    parse_position "$position"
    printf '%sx%s+%s+%s' "$DISPLAY_WIDTH" "$DISPLAY_HEIGHT" "$DISPLAY_X" "$DISPLAY_Y"
}

function geometry_for_both() {
    local external_mode="$EXTERNAL_MODE"
    if [ -n "$EXTERNAL_SCALE_FROM" ]; then
        external_mode="$EXTERNAL_SCALE_FROM"
    fi

    parse_size "$PRIMARY_MODE"
    local primary_width="$DISPLAY_WIDTH"
    local primary_height="$DISPLAY_HEIGHT"
    parse_position "$PRIMARY_POS"
    local primary_x="$DISPLAY_X"
    local primary_y="$DISPLAY_Y"

    parse_size "$external_mode"
    local external_width="$DISPLAY_WIDTH"
    local external_height="$DISPLAY_HEIGHT"
    parse_position "$EXTERNAL_POS"
    local external_x="$DISPLAY_X"
    local external_y="$DISPLAY_Y"

    local min_x=$(( primary_x < external_x ? primary_x : external_x ))
    local min_y=$(( primary_y < external_y ? primary_y : external_y ))
    local max_x=$(( primary_x + primary_width > external_x + external_width ? primary_x + primary_width : external_x + external_width ))
    local max_y=$(( primary_y + primary_height > external_y + external_height ? primary_y + primary_height : external_y + external_height ))

    printf '%sx%s+%s+%s' "$(( max_x - min_x ))" "$(( max_y - min_y ))" "$min_x" "$min_y"
}

function target_geometry() {
    local target="${2:-${SCREENSHOT_TARGET:-both}}"
    local external_mode="$EXTERNAL_MODE"
    if [ -n "$EXTERNAL_SCALE_FROM" ]; then
        external_mode="$EXTERNAL_SCALE_FROM"
    fi

    case "$target" in
        external)
            if is_connected "$EXTERNAL_NAME"; then
                geometry_for_display "$external_mode" "$EXTERNAL_POS"
            else
                geometry_for_display "$PRIMARY_MODE" "$PRIMARY_POS"
            fi
            ;;
        both)
            if is_connected "$EXTERNAL_NAME"; then
                geometry_for_both
            else
                geometry_for_display "$PRIMARY_MODE" "$PRIMARY_POS"
            fi
            ;;
        primary|*)
            geometry_for_display "$PRIMARY_MODE" "$PRIMARY_POS"
            ;;
    esac
}

# Main function
function shot() {

	check_dir

	file_loc="${screenshot_dir}$(date +%Y%m%d_%H%M%S).png"

	maim_command="$1"
	notif_message="$2"

	# Execute maim command
	${maim_command} "${file_loc}"

	# Exit if the user cancels the screenshot
	# So it means there's no new screenshot image file
	if [ ! -f "${file_loc}" ];
	then
		exit;
	fi

	# Copy to clipboard
	xclip -selection clipboard -t image/png -i "${screenshot_dir}"/`ls -1 -t "${screenshot_dir}" | head -1` &

	awesome-client "

	-- IMPORTANT NOTE: THIS PART OF THE SCRIPT IS LUA!
	naughty = require('naughty')
	awful = require('awful')
	beautiful = require('beautiful')
	dpi = beautiful.xresources.apply_dpi

	local open_image = naughty.action {
		name = 'Open',
	   	icon_only = false,
	}

	local open_folder = naughty.action {
		name = 'Open Folder',
	   	icon_only = false,
	}

	local delete_image = naughty.action {
		name = 'Delete',
	   	icon_only = false,
	}

	-- Execute the callback when 'Open' is pressed
	open_image:connect_signal('invoked', function()
		awful.spawn('xdg-open ' .. '${file_loc}', false)
	end)

	open_folder:connect_signal('invoked', function()
		awful.spawn('xdg-open ' .. '${screenshot_dir}', false)
	end)

	-- Execute the callback when 'Delete' is pressed
	delete_image:connect_signal('invoked', function()
		awful.spawn('gio trash ' .. '${file_loc}', false)
	end)

	-- Show notification
	naughty.notification ({
		app_name = 'Screenshot Tool',
		icon = '${file_loc}',
		timeout = 10,
		title = '<b>Snap!</b>',
		message = '${notif_message}',
		actions = { open_image, open_folder, delete_image }
	})
	"

}

# Check the args passed
if [ -z "$1" ] || ([ "$1" != 'full' ] && [ "$1" != 'area' ]);
then
	echo "
	Requires an argument:
	area 	- Area screenshot
	full 	- Fullscreen screenshot

	Optional second argument for full screenshots:
	primary | external | both

	Example:
	./snap area
	./snap full
	./snap full external
	"
elif [ "$1" = 'full' ];
then
	msg="Full screenshot saved and copied to clipboard!"
	shot "maim -u -m 1 -g $(target_geometry "$@")" "${msg}"
elif [ "$1" = 'area' ];
then
	msg='Area screenshot saved and copied to clipboard!'
	shot 'maim -u -s -n -m 1' "${msg}"
fi
