#!/usr/bin/env bash

## Author       : Aditya Shakya
## Github       : @adi1090x
## Modified by  : Ragu Manjegowda

## Get time and date
TIME="$(date +"%I:%M %p")"
DN=$(date +"%A")
MN=$(date +"%B")
DAY="$(date +"%d")"
MONTH="$(date +"%m")"
YEAR="$(date +"%Y")"

options="$DAY\n$MONTH\n$YEAR"

## Main
chosen="$(echo -e "$options" | $@ -p "   $DN, $TIME" -dmenu -selected-row 1)"
