#!/usr/bin/env bash

# Depends: Volctl
# Written by  : Ragu Manjegowda
# Github      : @ragu-manjegowda

set -e

trap 'echo "volctl error at line $LINENO" >&2' ERR

# Check if volctl Python app is already running, if so exit
if pgrep -f "python.*venv/bin/volctl" > /dev/null 2>&1; then
    exit
fi

VOLCTL_PATH=$HOME/.config/awesome/library/volctl

cd "$VOLCTL_PATH"

export GSETTINGS_SCHEMA_DIR=$VOLCTL_PATH/venv/share/glib-2.0/schemas
export XDG_DATA_DIRS=/usr/local/share:/usr/share

if [ ! -d "$VOLCTL_PATH/venv" ]; then
    uv venv --system-site-packages venv
fi

if [ ! -f "$VOLCTL_PATH/venv/bin/volctl" ]; then
    uv pip install "$VOLCTL_PATH" --python "$VOLCTL_PATH/venv/bin/python"
fi

if [ ! -d "$VOLCTL_PATH/venv/share/glib-2.0/schemas" ]; then
    mkdir "$VOLCTL_PATH/venv/share/glib-2.0/schemas"
fi

cp "$VOLCTL_PATH/data/apps.volctl.gschema.xml" "$VOLCTL_PATH/venv/share/glib-2.0/schemas"
glib-compile-schemas "$VOLCTL_PATH/venv/share/glib-2.0/schemas/" 2>/dev/null

# Wait for systray to be ready
sleep 2

exec "$VOLCTL_PATH/venv/bin/volctl" 2>/dev/null
