#!/bin/bash

# Based on https://stackoverflow.com/a/21756612
# following files are ignored for local changes
config update-index --assume-unchanged \
    .config/alacritty/colors.yml \
    .config/awesome/configuration/rofi/appmenu/rofi.rasi \
    .config/awesome/configuration/rofi/emojimenu/rofi.rasi \
    .config/awesome/configuration/rofi/global/icons/history.svg \
    .config/awesome/configuration/rofi/global/icons/result.svg \
    .config/awesome/configuration/rofi/global/icons/suggestion.svg \
    .config/awesome/configuration/rofi/runmenu/rofi.rasi \
    .config/awesome/configuration/rofi/time/rofi.rasi \
    .config/awesome/theme/icons/battery-charge.svg \
    .config/awesome/theme/icons/brightness-7.svg \
    .config/awesome/theme/icons/chart-areaspline.svg \
    .config/awesome/theme/icons/close.svg \
    .config/awesome/theme/icons/effects.svg \
    .config/awesome/theme/icons/harddisk.svg \
    .config/awesome/theme/icons/keyboard-brightness.svg \
    .config/awesome/theme/icons/layouts/dwindle.png \
    .config/awesome/theme/icons/layouts/floating.png \
    .config/awesome/theme/icons/layouts/fullscreen.png \
    .config/awesome/theme/icons/layouts/max.png \
    .config/awesome/theme/icons/layouts/tile.png \
    .config/awesome/theme/icons/lock.svg \
    .config/awesome/theme/icons/logout.svg \
    .config/awesome/theme/icons/magnify.svg \
    .config/awesome/theme/icons/memory.svg \
    .config/awesome/theme/icons/plus.svg \
    .config/awesome/theme/icons/power-hibernate.svg \
    .config/awesome/theme/icons/power-sleep.svg \
    .config/awesome/theme/icons/power.svg \
    .config/awesome/theme/icons/restart.svg \
    .config/awesome/theme/icons/ship-wheel.svg \
    .config/awesome/theme/icons/tag-list/close-small.svg \
    .config/awesome/theme/icons/tag-list/file-manager.svg \
    .config/awesome/theme/icons/tag-list/games.svg \
    .config/awesome/theme/icons/tag-list/graphics.svg \
    .config/awesome/theme/icons/tag-list/menu.svg \
    .config/awesome/theme/icons/tag-list/menu2.svg \
    .config/awesome/theme/icons/tag-list/multimedia.svg \
    .config/awesome/theme/icons/tag-list/sandbox.svg \
    .config/awesome/theme/icons/tag-list/social.svg \
    .config/awesome/theme/icons/tag-list/terminal.svg \
    .config/awesome/theme/icons/tag-list/text-editor.svg \
    .config/awesome/theme/icons/tags/1.png \
    .config/awesome/theme/icons/tags/2.png \
    .config/awesome/theme/icons/tags/3.png \
    .config/awesome/theme/icons/tags/4.png \
    .config/awesome/theme/icons/tags/5.png \
    .config/awesome/theme/icons/tags/6.png \
    .config/awesome/theme/icons/tags/7.png \
    .config/awesome/theme/icons/tags/8.png \
    .config/awesome/theme/icons/tags/9.png \
    .config/awesome/theme/icons/thermometer.svg \
    .config/awesome/theme/icons/toggled-off.svg \
    .config/awesome/theme/icons/toggled-on.svg \
    .config/awesome/theme/icons/volume-high.svg \
    .config/awesome/theme/icons/volume-muted.svg \
    .config/awesome/theme/init.lua \
    .config/awesome/utilities/awesome-last-ws \
    .config/awesome/widget/airplane-mode/icons/airplane-mode-off.svg \
    .config/awesome/widget/airplane-mode/icons/airplane-mode.svg \
    .config/awesome/widget/battery/icons/battery-alert.svg \
    .config/awesome/widget/battery/icons/battery-charging-10.svg \
    .config/awesome/widget/battery/icons/battery-charging-20.svg \
    .config/awesome/widget/battery/icons/battery-charging-30.svg \
    .config/awesome/widget/battery/icons/battery-charging-50.svg \
    .config/awesome/widget/battery/icons/battery-charging-60.svg \
    .config/awesome/widget/battery/icons/battery-charging-80.svg \
    .config/awesome/widget/battery/icons/battery-charging-90.svg \
    .config/awesome/widget/battery/icons/battery-discharging-100.svg \
    .config/awesome/widget/battery/icons/battery-discharging-20.svg \
    .config/awesome/widget/battery/icons/battery-discharging-30.svg \
    .config/awesome/widget/battery/icons/battery-discharging-50.svg \
    .config/awesome/widget/battery/icons/battery-discharging-60.svg \
    .config/awesome/widget/battery/icons/battery-discharging-80.svg \
    .config/awesome/widget/battery/icons/battery-discharging-90.svg \
    .config/awesome/widget/battery/icons/battery-fully-charged.svg \
    .config/awesome/widget/battery/icons/battery-unknown.svg \
    .config/awesome/widget/battery/icons/battery.svg \
    .config/awesome/widget/blue-light/icons/blue-light-off.svg \
    .config/awesome/widget/blue-light/icons/blue-light.svg \
    .config/awesome/widget/bluetooth-toggle/icons/bluetooth-off.svg \
    .config/awesome/widget/bluetooth-toggle/icons/bluetooth.svg \
    .config/awesome/widget/bluetooth-toggle/icons/loading.svg \
    .config/awesome/widget/blur-toggle/icons/effects-off.svg \
    .config/awesome/widget/control-center-switch/icons/control-center.svg \
    .config/awesome/widget/control-center-toggle/icons/control-center.svg \
    .config/awesome/widget/dont-disturb/disturb_status \
    .config/awesome/widget/dont-disturb/icons/dont-disturb.svg \
    .config/awesome/widget/dont-disturb/icons/notify.svg \
    .config/awesome/widget/email/icons/email-1.svg \
    .config/awesome/widget/email/icons/email-2.svg \
    .config/awesome/widget/email/icons/email-3.svg \
    .config/awesome/widget/email/icons/email-4.svg \
    .config/awesome/widget/email/icons/email-5.svg \
    .config/awesome/widget/email/icons/email-6.svg \
    .config/awesome/widget/email/icons/email-7.svg \
    .config/awesome/widget/email/icons/email-8.svg \
    .config/awesome/widget/email/icons/email-9+.svg \
    .config/awesome/widget/email/icons/email-9.svg \
    .config/awesome/widget/email/icons/email-unread.svg \
    .config/awesome/widget/email/icons/email.svg \
    .config/awesome/widget/info-center-toggle/icons/info-center.svg \
    .config/awesome/widget/notif-center/icons/clear_all.png \
    .config/awesome/widget/notif-center/icons/delete.svg \
    .config/awesome/widget/screen-recorder/icons/audio.svg \
    .config/awesome/widget/screen-recorder/icons/back.svg \
    .config/awesome/widget/screen-recorder/icons/close-screen.svg \
    .config/awesome/widget/screen-recorder/icons/recorder-countdown.svg \
    .config/awesome/widget/screen-recorder/icons/recorder-off.svg \
    .config/awesome/widget/screen-recorder/icons/recorder-on.svg \
    .config/awesome/widget/screen-recorder/icons/recording-button.svg \
    .config/awesome/widget/screen-recorder/icons/settings.svg \
    .config/awesome/widget/screen-recorder/icons/start-recording-button.svg \
    .config/awesome/widget/tray-toggle/icons/left-arrow.svg \
    .config/awesome/widget/tray-toggle/icons/right-arrow.svg \
    .config/awesome/widget/volume-slider/icons/volume-muted.png \
    .config/awesome/widget/weather/icons/d_rain.svg \
    .config/awesome/widget/weather/icons/dbroken_clouds.svg \
    .config/awesome/widget/weather/icons/dfew_clouds.svg \
    .config/awesome/widget/weather/icons/dmist.svg \
    .config/awesome/widget/weather/icons/dscattered_clouds.svg \
    .config/awesome/widget/weather/icons/dshower_rain.svg \
    .config/awesome/widget/weather/icons/dthunderstorm.svg \
    .config/awesome/widget/weather/icons/moon_icon.svg \
    .config/awesome/widget/weather/icons/n_rain.svg \
    .config/awesome/widget/weather/icons/nbroken_clouds.svg \
    .config/awesome/widget/weather/icons/nfew_clouds.svg \
    .config/awesome/widget/weather/icons/nmist.svg \
    .config/awesome/widget/weather/icons/nscattered_clouds.svg \
    .config/awesome/widget/weather/icons/nshower_rain.svg \
    .config/awesome/widget/weather/icons/nthunderstorm.svg \
    .config/awesome/widget/weather/icons/refresh.svg \
    .config/awesome/widget/weather/icons/snow.svg \
    .config/awesome/widget/weather/icons/sunrise.svg \
    .config/awesome/widget/weather/icons/sunset.svg \
    .config/awesome/widget/xdg-folders/icons/folder-documents.svg \
    .config/awesome/widget/xdg-folders/icons/folder-download.svg \
    .config/awesome/widget/xdg-folders/icons/folder-pictures.svg \
    .config/awesome/widget/xdg-folders/icons/folder-videos.svg \
    .config/awesome/widget/xdg-folders/icons/no.svg \
    .config/awesome/widget/xdg-folders/icons/open-folder.svg \
    .config/awesome/widget/xdg-folders/icons/user-home.svg \
    .config/awesome/widget/xdg-folders/icons/user-trash-empty.svg \
    .config/awesome/widget/xdg-folders/icons/user-trash-full.svg \
    .config/awesome/widget/xdg-folders/icons/yes.svg \
    .config/chrome-flags.conf \
    .config/rofi/config.rasi \
    .config/xsettingsd/xsettingsd.conf \
    .icons/default/index.theme
