#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                rm "$file" ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        esac
done

