# GStreamer source element name:
VIDEOSRC="icamerasrc"

# Output format, width, height, and frame rate:
FORMAT=NV12
WIDTH=1920
HEIGHT=1080
FRAMERATE=30/1

# Virtual video device name:
CARD_LABEL="V4L2 Loopback 1"
