_bootstrap_hooks=()
for _bootstrap_hook in "${HOOKS[@]}"; do
    if [[ "$_bootstrap_hook" == filesystems ]]; then
        _bootstrap_hooks+=(resume)
    fi
    _bootstrap_hooks+=("$_bootstrap_hook")
done
HOOKS=("${_bootstrap_hooks[@]}")
unset _bootstrap_hooks _bootstrap_hook
