#!/bin/sh

icon_charge_tier6='💚'
icon_charge_tier5='💜'
icon_charge_tier4='💙'
icon_charge_tier3='🧡'
icon_charge_tier2='💛'
icon_charge_tier1='🖤'

charge_icon() {
    percentage=$1
    percentage=${percentage%?}
	if [ $percentage -ge 95 ]; then
		echo "$icon_charge_tier6"
	elif [ $percentage -ge 80 ]; then
		echo "$icon_charge_tier5"
	elif [ $percentage -ge 60 ]; then
		echo "$icon_charge_tier4"
	elif [ $percentage -ge 40 ]; then
		echo "$icon_charge_tier3"
	elif [ $percentage -ge 20 ]; then
		echo "$icon_charge_tier2"
	else
		echo "$icon_charge_tier1"
	fi
}

command_exists() {
	local command="$1"
	type "$command" >/dev/null 2>&1
}

is_wsl() {
	version=$(</proc/version)
	if [[ "$version" == *"Microsoft"* || "$version" == *"microsoft"* ]]; then
		return 0
	else
		return 1
	fi
}

battery_percentage() {
    if is_wsl; then
		local battery
		battery=$(find /sys/class/power_supply/*/status | tail -n1)
		awk '{print tolower($0);}' "$battery"
	elif command_exists "pmset"; then
		pmset -g batt | grep -o "[0-9]\{1,3\}%"
	elif command_exists "acpi"; then
		acpi -b | grep -m 1 -Eo "[0-9]+%"
	elif command_exists "upower"; then
        # use DisplayDevice if available otherwise battery
		local battery=$(upower -e | grep -E 'battery|DisplayDevice'| tail -n1)
		if [ -z "$battery" ]; then
			return
		fi
		local percentage=$(upower -i $battery | awk '/percentage:/ {print $2}')
		if [ "$percentage" ]; then
			echo ${percentage%.*%}
			return
		fi
		local energy
		local energy_full
		energy=$(upower -i $battery | awk -v nrg="$energy" '/energy:/ {print nrg+$2}')
		energy_full=$(upower -i $battery | awk -v nrgfull="$energy_full" '/energy-full:/ {print nrgfull+$2}')
		if [ -n "$energy" ] && [ -n "$energy_full" ]; then
			echo $energy $energy_full | awk '{printf("%d%%", ($1/$2)*100)}'
		fi
	elif command_exists "termux-battery-status"; then
		termux-battery-status | jq -r '.percentage' | awk '{printf("%d%%", $1)}'
	elif command_exists "apm"; then
		apm -l
	fi
}


BATTERY_PERCENTAGE=`battery_percentage`
PRINT_ICON=`charge_icon $BATTERY_PERCENTAGE`

[ -z "$BATTERY_PERCENTAGE" ] && exit

echo ${PRINT_ICON}${BATTERY_PERCENTAGE}

