#!/bin/bash
#Script written for a Zathura Mac app by Ragu Manjegowda
#
##########################################
export LANG=en_CA.UTF-8

export HOMEBREW_PATH="/usr/local"
if [ -r "/opt/homebrew" ]; then
    export HOMEBREW_PATH="/opt/homebrew"
fi

$HOMEBREW_PATH/bin/zathura;
