If:
  PathMatch: [
    .git,
    apps/*,
    av/*,
    avddn/*,
    bazel-*/,
    benchmarks/*,
    ci/*,
    data/*,
    dazel-out/*,
    doc/*,
    external/*,
    lib*.so,
    partners/*,
    pilotnet/*,
    preFlightChecker/*,
    private/*,
    resources/*,
    scripts/*,
    share/*,
    swig/*,
    tools/experimental/localization_metrics/*
    tools/experimental/maps/*,
    ux/*,
  ]

Index:
  Background: Skip     # Disable slow background indexing of these files.

Diagnostics:
  Suppress: '*'
