#!/bin/bash

iface=$1

if [[ $iface != lo ]]; then
    case "$2" in
        up)
            systemctl start ntpd.service
        ;;
        down)
            systemctl stop ntpd.service
        ;;
    esac
fi
