[Login]
SleepOperation=suspend
HandlePowerKey=suspend
HandleLidSwitch=suspend
HandleLidSwitchExternalPower=suspend
HandleLidSwitchDocked=ignore
HandleHibernateKey=ignore
HandleHibernateKeyLongPress=ignore
HoldoffTimeoutSec=3min
