[Login]
SleepOperation=suspend-then-hibernate suspend hibernate
HandlePowerKey=suspend
HandleLidSwitch=suspend-then-hibernate
HandleLidSwitchExternalPower=suspend
HandleLidSwitchDocked=ignore
HoldoffTimeoutSec=3min
